package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const modulePath = "github.com/lengzhao/agentkit"

func main() {
	root, err := repoRoot()
	if err != nil {
		exit(err)
	}

	imports, err := collectImports(root)
	if err != nil {
		exit(err)
	}

	outPath := filepath.Join(root, "plugins", "all.go")
	if err := writeAllGo(outPath, imports); err != nil {
		exit(err)
	}
	fmt.Fprintf(os.Stderr, "gen-imports: wrote %s (%d imports)\n", outPath, len(imports))
}

func repoRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("resolve caller path")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..")), nil
}

func collectImports(root string) ([]string, error) {
	var imports []string
	for _, base := range []string{"plugins", "runtime"} {
		basePath := filepath.Join(root, base)
		err := filepath.WalkDir(basePath, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if !d.IsDir() {
				return nil
			}
			if path == basePath {
				return nil
			}
			ok, err := dirHasGoRegister(path)
			if err != nil {
				return err
			}
			if !ok {
				return nil
			}
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			imports = append(imports, modulePath+"/"+filepath.ToSlash(rel))
			return filepath.SkipDir
		})
		if err != nil {
			return nil, err
		}
	}

	sort.Strings(imports)
	return imports, nil
}

func dirHasGoRegister(dir string) (bool, error) {
	info, err := os.Stat(dir)
	if err != nil || !info.IsDir() {
		return false, err
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			return false, err
		}
		if strings.Contains(string(data), "pluginkit.Register(") {
			return true, nil
		}
	}
	return false, nil
}

func writeAllGo(path string, imports []string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen-imports. DO NOT EDIT.\n\n")
	buf.WriteString("package all\n\n")
	buf.WriteString("import (\n")
	for _, imp := range imports {
		fmt.Fprintf(&buf, "\t_ %q\n", imp)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile(path, formatted, 0o644)
}

func exit(err error) {
	fmt.Fprintf(os.Stderr, "gen-imports: %v\n", err)
	os.Exit(1)
}
