package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/lengzhao/agentkit/config"
)

func runScaffold(args []string) {
	if len(args) == 0 {
		printScaffoldUsage()
		os.Exit(2)
	}

	switch args[0] {
	case "tools":
		runScaffoldTools(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown scaffold target %q\n\n", args[0])
		printScaffoldUsage()
		os.Exit(2)
	}
}

func runScaffoldTools(args []string) {
	fs := flag.NewFlagSet("scaffold tools", flag.ExitOnError)
	out := fs.String("o", "", "write YAML to file (default stdout)")
	profile := fs.String("profile", string(config.ToolProfileDefault), "tools profile: default or subagent")
	whitelist := fs.String("whitelist", "", "comma-separated plugin kinds to include")
	blacklist := fs.String("blacklist", "", "comma-separated plugin kinds to exclude")
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "usage: agent scaffold tools [-profile default|subagent] [-o file] [-whitelist k1,k2] [-blacklist k3]\n")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		os.Exit(2)
	}

	opts := config.ToolsScaffoldOptions{
		Whitelist: splitCSVKinds(*whitelist),
		Blacklist: splitCSVKinds(*blacklist),
	}
	raw, err := config.ScaffoldToolsYAML(config.ToolProfile(*profile), opts)
	if err != nil {
		fatal("scaffold tools", err)
	}

	header := []byte("# generated by: agent scaffold tools\n# merge into config.base.yaml or use as L1 overlay\n\n")
	payload := append(header, raw...)
	if *out == "" {
		os.Stdout.Write(payload)
		return
	}
	if err := os.WriteFile(*out, payload, 0o644); err != nil {
		fatal("write scaffold output", err)
	}
	fmt.Printf("wrote %s\n", *out)
}

func printScaffoldUsage() {
	fmt.Fprintf(os.Stderr, `usage:
  agent scaffold tools [-profile default|subagent] [-o file] [-whitelist k1,k2] [-blacklist k3]

Examples:
  agent scaffold tools
  agent scaffold tools -profile subagent -o tools.subagent.generated.yaml
  agent scaffold tools -blacklist tool/send,tool/schedule
`)
}

func splitCSVKinds(csv string) []string {
	var out []string
	for _, part := range strings.Split(csv, ",") {
		if part = strings.TrimSpace(part); part != "" {
			out = append(out, part)
		}
	}
	return out
}
